name: Build PHP unified image
on:
  push:
    paths:
      - '.github/workflows/php-unified.yaml'
      - 'unified/8.0.Dockerfile'
      - 'unified/8.1.Dockerfile'
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  UPLOAD_REPOSITORY: ghcr.io/limpid-llc/

jobs:
  build-and-push-php-docker-images:
    runs-on:
      - ubuntu-20.04
    strategy:
      matrix:
       include:
         - php-type: "8.1"
           local-name: "unified-8.1"
           dockerfile: "unified/8.1.Dockerfile"
           upload-tag: "php-unified-8.1:latest"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build --pull --progress plain -t ${{ matrix.local-name }} -t ${UPLOAD_REPOSITORY}${{ matrix.upload-tag }} -f ${{ matrix.dockerfile }} .

      - name: Show PHP version and modules, installed in docker image
        run: docker run --rm ${{ matrix.local-name }} sh -c "php -v && php -m"

      - name: Push docker image to registry
        run: docker push ${UPLOAD_REPOSITORY}${{ matrix.upload-tag }}
